# Default config for sampling, epochs, parallelization, buffers, collectors, and batching.
# Keep in sync with RLSamplingConfig dataclass.
epoch: 100
step_per_epoch: 30000
batch_size: 64
training_num: 64
test_num: 10
buffer_size: 4096
step_per_collect: 2048
repeat_per_collect: 10
